@startmindmap
* 10th 
**[#LightGreen] Best <&star>
*** +2 Science \n in best college
****[#LightGreen] Best <&star>
***** JEE Coaching 
******[#LightGreen] Best <&star> 
******* IIT
********[#LightGreen] Best <&star>
******** Average 
******** Below Avg 
****** Average 
******* NIT 
******** Best 
********* FAANG
********** Best <&star> 
*********** Take Risks \n for Own Venture
********** Average
********** Below Avg
******** Average 
******** Below Avg
****** Below Avg 
******* State Eng. 
***** Mediacal Coaching 
**** Average
***** BSc 
**** Below Avg
** Average 
*** +2 Science \n in avg college
*** +2 Arts 
*** +2 Commerse 
** Below Avg 
*** Diploma

@endmindmap
