@startmindmap
* Grandmaster SDE
** Hard Skills
*** Domain knowledge
**** Crystal Clear Domain Knowledge
*** Tech Knowledge
**** Frontend
**** Infrastructure
***** DataBase
**** Backend
**** System Design
***** HLD
***** LLD
**** DS & Algo
*** Code Review
** Soft Skills
*** Fluent English
*** Good Story Telling
*** Crystal Clear Idea Sharing
*** Emotional Intelligence
*** Negotiation

** Leadership Skill
*** Bias for Action
*** Disagree and Commit
*** Team work and Collaboration
** Execution
*** Lighting fast execution
@endmindmap
