@startuml
legend right
  == Class Associations Legend ==
  -- Associations --
  * "--" : Association
  * "..>" : Dependency
  * "<|--" : Inheritance
  * "<|.." : Implement
  * "*--" : Composition (A is a composition of multiple B)
  * "o--" : Aggregation (A is an Aggregation of multiple B)
endlegend
@enduml